services:
  postgres:
    container_name: game-store-postgres
    image: postgres:17.2
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "NeneTsh3Po$"
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_DB: "game_store_app_db"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local